---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _pages/dejogmiglinks.md
  label: dejogmig links
- type: document
  path: _pages/instagram.md
  label: instagram.md
- type: directory
  path: ''
  label: all
  create: all
  match: "**/*"
  new_doc_ext: yaml
- type: directory
  path: _data/recipes
  label: Recipes
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - opskrift-data
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
  new_doc_ext: md
  templates:
  - opskrift
- type: directory
  path: _category
  label: Category
  create: all
  match: "**/*"
upload_dir: assets/images/uploads
public_path: "/assets/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
